name: Deploy on Merge to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest        
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-3
          role-to-assume: ${{secrets.THEO_LIVE_AWS_ARN}}

      - name: Run deploy command
        env:
          BUCKET: ${{ vars.THEO_LIVE_DEMO_BUCKET }}
          BUILD_DIR: ${{ vars.THEO_LIVE_DEMO_BUILD_FOLDER }}
          CLOUD_FRONT_ID: ${{secrets.THEO_LIVE_DEMO_CLOUD_FRONT_ID}}
        run: npm run deploy -- ${BUCKET} ${BUILD_DIR} ${CLOUD_FRONT_ID}
